CREATE TABLE DIM_AccToLanguage
	( AccToLanguage_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 100 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 100 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	EMail varchar2(100 char),
	Language_CD varchar2(10 char),
	DateLastChanged date NOT NULL, 
	PRIMARY KEY
	( AccToLanguage_ID )
 )
;

CREATE TABLE DIM_AccToVocab
	( Vocab varchar2(60 char) NOT NULL,
	Language_CD varchar2(10 char),
	AccToLanguage_ID number(10,0) NOT NULL,
	LearningLVL number(10,0) NOT NULL,
	DateLastChanged date NOT NULL, 
	PRIMARY KEY
	( Vocab )
 )
;

CREATE TABLE DIM_AccType
	( AccType_CD varchar2(10 char) NOT NULL,
	AccType_DESCR varchar2(100 char) NOT NULL,
	DateLastChanged date NOT NULL, 
	PRIMARY KEY
	( AccType_CD )
 )
;

CREATE TABLE DIM_Account
	( EMail varchar2(100 char) NOT NULL,
	Password varchar2(60 char) NOT NULL,
	EMail_Parent varchar2(100 char),
	AccType_CD varchar2(10 char) NOT NULL,
	FirstName varchar2(60 char) NOT NULL,
	LastName varchar2(60 char) NOT NULL,
	Age number(10,0) NOT NULL,
	DateLastChanged date NOT NULL,
	LearningType_CD_50073 varchar2(10 char) NOT NULL,
	Gender_CD varchar2(10 char) NOT NULL, 
	PRIMARY KEY
	( EMail )
 )
;

CREATE TABLE DIM_Classes
	( Class_CD varchar2(10 char) NOT NULL,
	Class_DESCR varchar2(100 char) NOT NULL,
	DateLastChanged date NOT NULL, 
	PRIMARY KEY
	( Class_CD )
 )
;

CREATE TABLE DIM_Gender
	( Gender_CD varchar2(10 char) NOT NULL,
	Gender_DESCR varchar2(100 char) NOT NULL,
	DateLastChanged date NOT NULL, 
	PRIMARY KEY
	( Gender_CD )
 )
;

CREATE TABLE DIM_Language
	( Language_CD varchar2(10 char) NOT NULL,
	Language_DESCR varchar2(100 char) NOT NULL,
	DateLastChanged date NOT NULL, 
	PRIMARY KEY
	( Language_CD )
 )
;

CREATE TABLE DIM_LearningType
	( LearningType_CD varchar2(10 char) NOT NULL,
	LearningType_DESCR varchar2(100 char) NOT NULL,
	DateLastChanged date NOT NULL, 
	PRIMARY KEY
	( LearningType_CD )
 )
;

CREATE TABLE DIM_Vocab
	( Vocab varchar2(60 char) NOT NULL,
	Language_CD varchar2(10 char) NOT NULL,
	Class_CD varchar2(10 char) NOT NULL,
	Translation varchar2(60 char) NOT NULL,
	DateLastChanged date NOT NULL, 
	PRIMARY KEY
	( Vocab,
	Language_CD )
 )
;

